/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://github.com/google/apis-client-generator/
 * (build: 2016-05-27 16:00:31 UTC)
 * on 2016-07-06 at 19:30:55 UTC 
 * Modify at your own risk.
 */

package com.appspot.recipex_1281.recipexServerApi.model;

/**
 * Message to return a list of Prescriptions Summary: This message class is intended to be a wrapper
 * for a response message which returns as additional payload a list of PrescriptionInfoMessage.
 * Attributes: prescriptions = List of PrescriptionInfoMessage to be returned response =
 * DefaultResponseMessage containing the response
 *
 * <p> This is the Java data model class that specifies how to parse/serialize into the JSON that is
 * transmitted over HTTP when working with the recipexServerApi. For a detailed explanation see:
 * <a href="https://developers.google.com/api-client-library/java/google-http-java-client/json">https://developers.google.com/api-client-library/java/google-http-java-client/json</a>
 * </p>
 *
 * @author Google, Inc.
 */
@SuppressWarnings("javadoc")
public final class MainUserPrescriptionsMessage extends com.google.api.client.json.GenericJson {

  /**
   * Message to return all the Prescription's informations Summary: This message class is used to
   * update the informations of a specific Prescription entity. Attributes: id = Datastore id of the
   * Prescription entity name = Name of the Prescription's drug to take active_ingr_key = Key of the
   * Prescription's Active Ingredient entity active_ingr_name = Name of the drug's Active Ingredient
   * of the Prescription kind = Kind of the Prescription's drug dose = Dose of the Prescription's
   * drug units = Unit of measure of the drug's dose quantity = Number of assumptions per day recipe
   * = Boolean that states if the Prescription's drug need a medical recipe or not pil = URL of the
   * patient information leaflet (PIL) of the Prescription's drug caregiver_id = Datastore id of the
   * User's entity of the Caregiver caregiver_user_id = Datastore id of the Caregiver's entity
   * caregiver_name = Name of the Caregiver caregiver_surname = Surname of the Caregiver
   * caregiver_mail = Email of the Caregiver caregiver_job = Kind of Caregiver (PC Physician,
   * Visiting Nurse or Caregiver) seen = Boolean value to track if the User saw the prescription or
   * not calendarIds = Google Calendar ids of the Prescription's events response =
   * DefaultResponseMessage containing the response
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.util.List<MainPrescriptionInfoMessage> prescriptions;

  /**
   * A generic response message Summary: This message class is intended for returning a generic
   * response. Attributes: code = HTTP code of the response [REQUIRED] message = Text message of the
   * response [REQUIRED] doOperation = Boolean value to determine if there's an operation to do
   * according to the response payload = Optional textual payload of the response user =
   * RegisterUserMessage of a related invocation
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private MainDefaultResponseMessage response;

  /**
   * Message to return all the Prescription's informations Summary: This message class is used to
   * update the informations of a specific Prescription entity. Attributes: id = Datastore id of the
   * Prescription entity name = Name of the Prescription's drug to take active_ingr_key = Key of the
   * Prescription's Active Ingredient entity active_ingr_name = Name of the drug's Active Ingredient
   * of the Prescription kind = Kind of the Prescription's drug dose = Dose of the Prescription's
   * drug units = Unit of measure of the drug's dose quantity = Number of assumptions per day recipe
   * = Boolean that states if the Prescription's drug need a medical recipe or not pil = URL of the
   * patient information leaflet (PIL) of the Prescription's drug caregiver_id = Datastore id of the
   * User's entity of the Caregiver caregiver_user_id = Datastore id of the Caregiver's entity
   * caregiver_name = Name of the Caregiver caregiver_surname = Surname of the Caregiver
   * caregiver_mail = Email of the Caregiver caregiver_job = Kind of Caregiver (PC Physician,
   * Visiting Nurse or Caregiver) seen = Boolean value to track if the User saw the prescription or
   * not calendarIds = Google Calendar ids of the Prescription's events response =
   * DefaultResponseMessage containing the response
   * @return value or {@code null} for none
   */
  public java.util.List<MainPrescriptionInfoMessage> getPrescriptions() {
    return prescriptions;
  }

  /**
   * Message to return all the Prescription's informations Summary: This message class is used to
   * update the informations of a specific Prescription entity. Attributes: id = Datastore id of the
   * Prescription entity name = Name of the Prescription's drug to take active_ingr_key = Key of the
   * Prescription's Active Ingredient entity active_ingr_name = Name of the drug's Active Ingredient
   * of the Prescription kind = Kind of the Prescription's drug dose = Dose of the Prescription's
   * drug units = Unit of measure of the drug's dose quantity = Number of assumptions per day recipe
   * = Boolean that states if the Prescription's drug need a medical recipe or not pil = URL of the
   * patient information leaflet (PIL) of the Prescription's drug caregiver_id = Datastore id of the
   * User's entity of the Caregiver caregiver_user_id = Datastore id of the Caregiver's entity
   * caregiver_name = Name of the Caregiver caregiver_surname = Surname of the Caregiver
   * caregiver_mail = Email of the Caregiver caregiver_job = Kind of Caregiver (PC Physician,
   * Visiting Nurse or Caregiver) seen = Boolean value to track if the User saw the prescription or
   * not calendarIds = Google Calendar ids of the Prescription's events response =
   * DefaultResponseMessage containing the response
   * @param prescriptions prescriptions or {@code null} for none
   */
  public MainUserPrescriptionsMessage setPrescriptions(java.util.List<MainPrescriptionInfoMessage> prescriptions) {
    this.prescriptions = prescriptions;
    return this;
  }

  /**
   * A generic response message Summary: This message class is intended for returning a generic
   * response. Attributes: code = HTTP code of the response [REQUIRED] message = Text message of the
   * response [REQUIRED] doOperation = Boolean value to determine if there's an operation to do
   * according to the response payload = Optional textual payload of the response user =
   * RegisterUserMessage of a related invocation
   * @return value or {@code null} for none
   */
  public MainDefaultResponseMessage getResponse() {
    return response;
  }

  /**
   * A generic response message Summary: This message class is intended for returning a generic
   * response. Attributes: code = HTTP code of the response [REQUIRED] message = Text message of the
   * response [REQUIRED] doOperation = Boolean value to determine if there's an operation to do
   * according to the response payload = Optional textual payload of the response user =
   * RegisterUserMessage of a related invocation
   * @param response response or {@code null} for none
   */
  public MainUserPrescriptionsMessage setResponse(MainDefaultResponseMessage response) {
    this.response = response;
    return this;
  }

  @Override
  public MainUserPrescriptionsMessage set(String fieldName, Object value) {
    return (MainUserPrescriptionsMessage) super.set(fieldName, value);
  }

  @Override
  public MainUserPrescriptionsMessage clone() {
    return (MainUserPrescriptionsMessage) super.clone();
  }

}
