/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://github.com/google/apis-client-generator/
 * (build: 2016-05-27 16:00:31 UTC)
 * on 2016-07-06 at 19:30:55 UTC 
 * Modify at your own risk.
 */

package com.appspot.recipex_1281.recipexServerApi.model;

/**
 * Message to return a list of Measurements Summary: This message class is intended to be a wrapper
 * for a response message which returns as additional payload a list of MeasurementInfoMessage.
 * Attributes: measurement = List of MeasurementInfoMessage to be returned response =
 * DefaultResponseMessage containing the response
 *
 * <p> This is the Java data model class that specifies how to parse/serialize into the JSON that is
 * transmitted over HTTP when working with the recipexServerApi. For a detailed explanation see:
 * <a href="https://developers.google.com/api-client-library/java/google-http-java-client/json">https://developers.google.com/api-client-library/java/google-http-java-client/json</a>
 * </p>
 *
 * @author Google, Inc.
 */
@SuppressWarnings("javadoc")
public final class MainUserMeasurementsMessage extends com.google.api.client.json.GenericJson {

  /**
   * Message to return all Measurement's informations Summary: This message class is intended to
   * return all the informations stored for a specific Measurement entity. Attributes: id =
   * Datastore id of the Measurement entity kind = Measurement's kind systolic = Systolic pressure
   * [PRESENT IF KIND = BP] diastolic = Diastolic pressure [PRESENT IF KIND = BP] bpm = Heart beats
   * per minute [PRESENT IF KIND = HR] respirations = Respirations done per minute [PRESENT IF KIND
   * = RR] spo2 = Pulse Oximeter Oxigen Saturation [PRESENT IF KIND = SpO2] hgt = Blood Sugar level
   * [REQUIRED IF KIND = HGT] degrees = Body temperature (in Celsius degrees) [PRESENT IF KIND =
   * TMP] nrs = Pain level (0-10 scale) [PRESENT IF KIND = PAIN] chl_level = Cholesterol level
   * [PRESENT IF KIND = CHL] note = Measurement's additional notes by the user calendar_id = Google
   * Calendar's id of the measurements event
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.util.List<MainMeasurementInfoMessage> measurements;

  /**
   * A generic response message Summary: This message class is intended for returning a generic
   * response. Attributes: code = HTTP code of the response [REQUIRED] message = Text message of the
   * response [REQUIRED] doOperation = Boolean value to determine if there's an operation to do
   * according to the response payload = Optional textual payload of the response user =
   * RegisterUserMessage of a related invocation
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private MainDefaultResponseMessage response;

  /**
   * Message to return all Measurement's informations Summary: This message class is intended to
   * return all the informations stored for a specific Measurement entity. Attributes: id =
   * Datastore id of the Measurement entity kind = Measurement's kind systolic = Systolic pressure
   * [PRESENT IF KIND = BP] diastolic = Diastolic pressure [PRESENT IF KIND = BP] bpm = Heart beats
   * per minute [PRESENT IF KIND = HR] respirations = Respirations done per minute [PRESENT IF KIND
   * = RR] spo2 = Pulse Oximeter Oxigen Saturation [PRESENT IF KIND = SpO2] hgt = Blood Sugar level
   * [REQUIRED IF KIND = HGT] degrees = Body temperature (in Celsius degrees) [PRESENT IF KIND =
   * TMP] nrs = Pain level (0-10 scale) [PRESENT IF KIND = PAIN] chl_level = Cholesterol level
   * [PRESENT IF KIND = CHL] note = Measurement's additional notes by the user calendar_id = Google
   * Calendar's id of the measurements event
   * @return value or {@code null} for none
   */
  public java.util.List<MainMeasurementInfoMessage> getMeasurements() {
    return measurements;
  }

  /**
   * Message to return all Measurement's informations Summary: This message class is intended to
   * return all the informations stored for a specific Measurement entity. Attributes: id =
   * Datastore id of the Measurement entity kind = Measurement's kind systolic = Systolic pressure
   * [PRESENT IF KIND = BP] diastolic = Diastolic pressure [PRESENT IF KIND = BP] bpm = Heart beats
   * per minute [PRESENT IF KIND = HR] respirations = Respirations done per minute [PRESENT IF KIND
   * = RR] spo2 = Pulse Oximeter Oxigen Saturation [PRESENT IF KIND = SpO2] hgt = Blood Sugar level
   * [REQUIRED IF KIND = HGT] degrees = Body temperature (in Celsius degrees) [PRESENT IF KIND =
   * TMP] nrs = Pain level (0-10 scale) [PRESENT IF KIND = PAIN] chl_level = Cholesterol level
   * [PRESENT IF KIND = CHL] note = Measurement's additional notes by the user calendar_id = Google
   * Calendar's id of the measurements event
   * @param measurements measurements or {@code null} for none
   */
  public MainUserMeasurementsMessage setMeasurements(java.util.List<MainMeasurementInfoMessage> measurements) {
    this.measurements = measurements;
    return this;
  }

  /**
   * A generic response message Summary: This message class is intended for returning a generic
   * response. Attributes: code = HTTP code of the response [REQUIRED] message = Text message of the
   * response [REQUIRED] doOperation = Boolean value to determine if there's an operation to do
   * according to the response payload = Optional textual payload of the response user =
   * RegisterUserMessage of a related invocation
   * @return value or {@code null} for none
   */
  public MainDefaultResponseMessage getResponse() {
    return response;
  }

  /**
   * A generic response message Summary: This message class is intended for returning a generic
   * response. Attributes: code = HTTP code of the response [REQUIRED] message = Text message of the
   * response [REQUIRED] doOperation = Boolean value to determine if there's an operation to do
   * according to the response payload = Optional textual payload of the response user =
   * RegisterUserMessage of a related invocation
   * @param response response or {@code null} for none
   */
  public MainUserMeasurementsMessage setResponse(MainDefaultResponseMessage response) {
    this.response = response;
    return this;
  }

  @Override
  public MainUserMeasurementsMessage set(String fieldName, Object value) {
    return (MainUserMeasurementsMessage) super.set(fieldName, value);
  }

  @Override
  public MainUserMeasurementsMessage clone() {
    return (MainUserMeasurementsMessage) super.clone();
  }

}
