/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://github.com/google/apis-client-generator/
 * (build: 2016-05-27 16:00:31 UTC)
 * on 2016-07-06 at 19:30:55 UTC 
 * Modify at your own risk.
 */

package com.appspot.recipex_1281.recipexServerApi.model;

/**
 * Message to return User's main informations Summary: This message class is intended to return the
 * most important informations of a specific User entity. Attributes: id = Datastore id of the User
 * entity caregiver_id = Datastore id of the corresponding Caregiver entity [IF PRESENT] name = Name
 * of the User entity surname = Surname of the User entity email = Email of the User entity pic =
 * Profile pic of the User entity field = Field of specialization of the Caregiver entity [IF
 * PRESENT] calendarid = Google Calendar id of the User's calendar
 *
 * <p> This is the Java data model class that specifies how to parse/serialize into the JSON that is
 * transmitted over HTTP when working with the recipexServerApi. For a detailed explanation see:
 * <a href="https://developers.google.com/api-client-library/java/google-http-java-client/json">https://developers.google.com/api-client-library/java/google-http-java-client/json</a>
 * </p>
 *
 * @author Google, Inc.
 */
@SuppressWarnings("javadoc")
public final class MainUserMainInfoMessage extends com.google.api.client.json.GenericJson {

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String calendarId;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key("caregiver_id") @com.google.api.client.json.JsonString
  private java.lang.Long caregiverId;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String email;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String field;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key @com.google.api.client.json.JsonString
  private java.lang.Long id;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String name;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String pic;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String surname;

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getCalendarId() {
    return calendarId;
  }

  /**
   * @param calendarId calendarId or {@code null} for none
   */
  public MainUserMainInfoMessage setCalendarId(java.lang.String calendarId) {
    this.calendarId = calendarId;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Long getCaregiverId() {
    return caregiverId;
  }

  /**
   * @param caregiverId caregiverId or {@code null} for none
   */
  public MainUserMainInfoMessage setCaregiverId(java.lang.Long caregiverId) {
    this.caregiverId = caregiverId;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getEmail() {
    return email;
  }

  /**
   * @param email email or {@code null} for none
   */
  public MainUserMainInfoMessage setEmail(java.lang.String email) {
    this.email = email;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getField() {
    return field;
  }

  /**
   * @param field field or {@code null} for none
   */
  public MainUserMainInfoMessage setField(java.lang.String field) {
    this.field = field;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Long getId() {
    return id;
  }

  /**
   * @param id id or {@code null} for none
   */
  public MainUserMainInfoMessage setId(java.lang.Long id) {
    this.id = id;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getName() {
    return name;
  }

  /**
   * @param name name or {@code null} for none
   */
  public MainUserMainInfoMessage setName(java.lang.String name) {
    this.name = name;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getPic() {
    return pic;
  }

  /**
   * @param pic pic or {@code null} for none
   */
  public MainUserMainInfoMessage setPic(java.lang.String pic) {
    this.pic = pic;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getSurname() {
    return surname;
  }

  /**
   * @param surname surname or {@code null} for none
   */
  public MainUserMainInfoMessage setSurname(java.lang.String surname) {
    this.surname = surname;
    return this;
  }

  @Override
  public MainUserMainInfoMessage set(String fieldName, Object value) {
    return (MainUserMainInfoMessage) super.set(fieldName, value);
  }

  @Override
  public MainUserMainInfoMessage clone() {
    return (MainUserMainInfoMessage) super.clone();
  }

}
