/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://github.com/google/apis-client-generator/
 * (build: 2016-05-27 16:00:31 UTC)
 * on 2016-07-06 at 19:30:55 UTC 
 * Modify at your own risk.
 */

package com.appspot.recipex_1281.recipexServerApi.model;

/**
 * Message to return all Message's informations Summary: This message class is intended to return
 * all the informations stored for a specific Message entity. Attributes: id = Datastore id of the
 * Message entity sender = Datastore id of the User sender entity of the Message receiver =
 * Datastore id of the User receiver entity of the Message message = Text of the message has_read =
 * Boolean value to track if the message has been read measurement = Datastore id of the Measurement
 * entity of the Message
 *
 * <p> This is the Java data model class that specifies how to parse/serialize into the JSON that is
 * transmitted over HTTP when working with the recipexServerApi. For a detailed explanation see:
 * <a href="https://developers.google.com/api-client-library/java/google-http-java-client/json">https://developers.google.com/api-client-library/java/google-http-java-client/json</a>
 * </p>
 *
 * @author Google, Inc.
 */
@SuppressWarnings("javadoc")
public final class MainMessageInfoMessage extends com.google.api.client.json.GenericJson {

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.Boolean hasRead;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key @com.google.api.client.json.JsonString
  private java.lang.Long id;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key @com.google.api.client.json.JsonString
  private java.lang.Long measurement;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String message;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key @com.google.api.client.json.JsonString
  private java.lang.Long receiver;

  /**
   * A generic response message Summary: This message class is intended for returning a generic
   * response. Attributes: code = HTTP code of the response [REQUIRED] message = Text message of the
   * response [REQUIRED] doOperation = Boolean value to determine if there's an operation to do
   * according to the response payload = Optional textual payload of the response user =
   * RegisterUserMessage of a related invocation
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private MainDefaultResponseMessage response;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key @com.google.api.client.json.JsonString
  private java.lang.Long sender;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key("sender_pic")
  private java.lang.String senderPic;

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Boolean getHasRead() {
    return hasRead;
  }

  /**
   * @param hasRead hasRead or {@code null} for none
   */
  public MainMessageInfoMessage setHasRead(java.lang.Boolean hasRead) {
    this.hasRead = hasRead;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Long getId() {
    return id;
  }

  /**
   * @param id id or {@code null} for none
   */
  public MainMessageInfoMessage setId(java.lang.Long id) {
    this.id = id;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Long getMeasurement() {
    return measurement;
  }

  /**
   * @param measurement measurement or {@code null} for none
   */
  public MainMessageInfoMessage setMeasurement(java.lang.Long measurement) {
    this.measurement = measurement;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getMessage() {
    return message;
  }

  /**
   * @param message message or {@code null} for none
   */
  public MainMessageInfoMessage setMessage(java.lang.String message) {
    this.message = message;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Long getReceiver() {
    return receiver;
  }

  /**
   * @param receiver receiver or {@code null} for none
   */
  public MainMessageInfoMessage setReceiver(java.lang.Long receiver) {
    this.receiver = receiver;
    return this;
  }

  /**
   * A generic response message Summary: This message class is intended for returning a generic
   * response. Attributes: code = HTTP code of the response [REQUIRED] message = Text message of the
   * response [REQUIRED] doOperation = Boolean value to determine if there's an operation to do
   * according to the response payload = Optional textual payload of the response user =
   * RegisterUserMessage of a related invocation
   * @return value or {@code null} for none
   */
  public MainDefaultResponseMessage getResponse() {
    return response;
  }

  /**
   * A generic response message Summary: This message class is intended for returning a generic
   * response. Attributes: code = HTTP code of the response [REQUIRED] message = Text message of the
   * response [REQUIRED] doOperation = Boolean value to determine if there's an operation to do
   * according to the response payload = Optional textual payload of the response user =
   * RegisterUserMessage of a related invocation
   * @param response response or {@code null} for none
   */
  public MainMessageInfoMessage setResponse(MainDefaultResponseMessage response) {
    this.response = response;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Long getSender() {
    return sender;
  }

  /**
   * @param sender sender or {@code null} for none
   */
  public MainMessageInfoMessage setSender(java.lang.Long sender) {
    this.sender = sender;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getSenderPic() {
    return senderPic;
  }

  /**
   * @param senderPic senderPic or {@code null} for none
   */
  public MainMessageInfoMessage setSenderPic(java.lang.String senderPic) {
    this.senderPic = senderPic;
    return this;
  }

  @Override
  public MainMessageInfoMessage set(String fieldName, Object value) {
    return (MainMessageInfoMessage) super.set(fieldName, value);
  }

  @Override
  public MainMessageInfoMessage clone() {
    return (MainMessageInfoMessage) super.clone();
  }

}
