/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://github.com/google/apis-client-generator/
 * (build: 2016-05-27 16:00:31 UTC)
 * on 2016-07-06 at 19:30:55 UTC 
 * Modify at your own risk.
 */

package com.appspot.recipex_1281.recipexServerApi.model;

/**
 * A generic response message Summary: This message class is intended for returning a generic
 * response. Attributes: code = HTTP code of the response [REQUIRED] message = Text message of the
 * response [REQUIRED] doOperation = Boolean value to determine if there's an operation to do
 * according to the response payload = Optional textual payload of the response user =
 * RegisterUserMessage of a related invocation
 *
 * <p> This is the Java data model class that specifies how to parse/serialize into the JSON that is
 * transmitted over HTTP when working with the recipexServerApi. For a detailed explanation see:
 * <a href="https://developers.google.com/api-client-library/java/google-http-java-client/json">https://developers.google.com/api-client-library/java/google-http-java-client/json</a>
 * </p>
 *
 * @author Google, Inc.
 */
@SuppressWarnings("javadoc")
public final class MainDefaultResponseMessage extends com.google.api.client.json.GenericJson {

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String code;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.Boolean doOperation;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String message;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String payload;

  /**
   * Message to register a User Summary: This Message Class is intended for register a User within
   * the application. Attributes: email = User's email [REQUIRED] name = User's first name
   * [REQUIRED] surname = User's last name [REQUIRED] birth = User's birth [REQUIRED] pic = URL to
   * User's profile pic [REQUIRED] sex = User's gender [REQUIRED] city = User's city address =
   * User's address personal_num = User's personal phone number field = Caregiver's field of
   * specilization [REQUIRED IF REGISTERING A CAREGIVER] years_exp = Caregiver's years of experience
   * place = Caregiver's place of work business_num = Caregivers' business phone number bio =
   * Caregiver short biography available = Caregiver's avalable days of the week calendarId = Id of
   * the User's Google Calendar used by the mobile application
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private MainRegisterUserMessage user;

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getCode() {
    return code;
  }

  /**
   * @param code code or {@code null} for none
   */
  public MainDefaultResponseMessage setCode(java.lang.String code) {
    this.code = code;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Boolean getDoOperation() {
    return doOperation;
  }

  /**
   * @param doOperation doOperation or {@code null} for none
   */
  public MainDefaultResponseMessage setDoOperation(java.lang.Boolean doOperation) {
    this.doOperation = doOperation;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getMessage() {
    return message;
  }

  /**
   * @param message message or {@code null} for none
   */
  public MainDefaultResponseMessage setMessage(java.lang.String message) {
    this.message = message;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getPayload() {
    return payload;
  }

  /**
   * @param payload payload or {@code null} for none
   */
  public MainDefaultResponseMessage setPayload(java.lang.String payload) {
    this.payload = payload;
    return this;
  }

  /**
   * Message to register a User Summary: This Message Class is intended for register a User within
   * the application. Attributes: email = User's email [REQUIRED] name = User's first name
   * [REQUIRED] surname = User's last name [REQUIRED] birth = User's birth [REQUIRED] pic = URL to
   * User's profile pic [REQUIRED] sex = User's gender [REQUIRED] city = User's city address =
   * User's address personal_num = User's personal phone number field = Caregiver's field of
   * specilization [REQUIRED IF REGISTERING A CAREGIVER] years_exp = Caregiver's years of experience
   * place = Caregiver's place of work business_num = Caregivers' business phone number bio =
   * Caregiver short biography available = Caregiver's avalable days of the week calendarId = Id of
   * the User's Google Calendar used by the mobile application
   * @return value or {@code null} for none
   */
  public MainRegisterUserMessage getUser() {
    return user;
  }

  /**
   * Message to register a User Summary: This Message Class is intended for register a User within
   * the application. Attributes: email = User's email [REQUIRED] name = User's first name
   * [REQUIRED] surname = User's last name [REQUIRED] birth = User's birth [REQUIRED] pic = URL to
   * User's profile pic [REQUIRED] sex = User's gender [REQUIRED] city = User's city address =
   * User's address personal_num = User's personal phone number field = Caregiver's field of
   * specilization [REQUIRED IF REGISTERING A CAREGIVER] years_exp = Caregiver's years of experience
   * place = Caregiver's place of work business_num = Caregivers' business phone number bio =
   * Caregiver short biography available = Caregiver's avalable days of the week calendarId = Id of
   * the User's Google Calendar used by the mobile application
   * @param user user or {@code null} for none
   */
  public MainDefaultResponseMessage setUser(MainRegisterUserMessage user) {
    this.user = user;
    return this;
  }

  @Override
  public MainDefaultResponseMessage set(String fieldName, Object value) {
    return (MainDefaultResponseMessage) super.set(fieldName, value);
  }

  @Override
  public MainDefaultResponseMessage clone() {
    return (MainDefaultResponseMessage) super.clone();
  }

}
