/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://github.com/google/apis-client-generator/
 * (build: 2016-05-27 16:00:31 UTC)
 * on 2016-07-06 at 19:30:55 UTC 
 * Modify at your own risk.
 */

package com.appspot.recipex_1281.recipexServerApi.model;

/**
 * Message to return the User's amount of unseen informations Summary: This message class is used to
 * return informations about the amount of unseen informations for a specific User entity.
 * Attributes: num_messages = Number of unseen Messages num_requests = Number of pending Requests
 * num_prescriptions = Number of unseen Prescriptions toRemove = List of E-Mails of Users to be
 * removed from User's Google Calendar response = DefaultResponseMessage containing the response
 *
 * <p> This is the Java data model class that specifies how to parse/serialize into the JSON that is
 * transmitted over HTTP when working with the recipexServerApi. For a detailed explanation see:
 * <a href="https://developers.google.com/api-client-library/java/google-http-java-client/json">https://developers.google.com/api-client-library/java/google-http-java-client/json</a>
 * </p>
 *
 * @author Google, Inc.
 */
@SuppressWarnings("javadoc")
public final class MainUserUnseenInfoMessage extends com.google.api.client.json.GenericJson {

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key("num_messages") @com.google.api.client.json.JsonString
  private java.lang.Long numMessages;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key("num_prescriptions") @com.google.api.client.json.JsonString
  private java.lang.Long numPrescriptions;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key("num_requests") @com.google.api.client.json.JsonString
  private java.lang.Long numRequests;

  /**
   * A generic response message Summary: This message class is intended for returning a generic
   * response. Attributes: code = HTTP code of the response [REQUIRED] message = Text message of the
   * response [REQUIRED] doOperation = Boolean value to determine if there's an operation to do
   * according to the response payload = Optional textual payload of the response user =
   * RegisterUserMessage of a related invocation
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private MainDefaultResponseMessage response;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.util.List<java.lang.String> toRemove;

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Long getNumMessages() {
    return numMessages;
  }

  /**
   * @param numMessages numMessages or {@code null} for none
   */
  public MainUserUnseenInfoMessage setNumMessages(java.lang.Long numMessages) {
    this.numMessages = numMessages;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Long getNumPrescriptions() {
    return numPrescriptions;
  }

  /**
   * @param numPrescriptions numPrescriptions or {@code null} for none
   */
  public MainUserUnseenInfoMessage setNumPrescriptions(java.lang.Long numPrescriptions) {
    this.numPrescriptions = numPrescriptions;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Long getNumRequests() {
    return numRequests;
  }

  /**
   * @param numRequests numRequests or {@code null} for none
   */
  public MainUserUnseenInfoMessage setNumRequests(java.lang.Long numRequests) {
    this.numRequests = numRequests;
    return this;
  }

  /**
   * A generic response message Summary: This message class is intended for returning a generic
   * response. Attributes: code = HTTP code of the response [REQUIRED] message = Text message of the
   * response [REQUIRED] doOperation = Boolean value to determine if there's an operation to do
   * according to the response payload = Optional textual payload of the response user =
   * RegisterUserMessage of a related invocation
   * @return value or {@code null} for none
   */
  public MainDefaultResponseMessage getResponse() {
    return response;
  }

  /**
   * A generic response message Summary: This message class is intended for returning a generic
   * response. Attributes: code = HTTP code of the response [REQUIRED] message = Text message of the
   * response [REQUIRED] doOperation = Boolean value to determine if there's an operation to do
   * according to the response payload = Optional textual payload of the response user =
   * RegisterUserMessage of a related invocation
   * @param response response or {@code null} for none
   */
  public MainUserUnseenInfoMessage setResponse(MainDefaultResponseMessage response) {
    this.response = response;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.util.List<java.lang.String> getToRemove() {
    return toRemove;
  }

  /**
   * @param toRemove toRemove or {@code null} for none
   */
  public MainUserUnseenInfoMessage setToRemove(java.util.List<java.lang.String> toRemove) {
    this.toRemove = toRemove;
    return this;
  }

  @Override
  public MainUserUnseenInfoMessage set(String fieldName, Object value) {
    return (MainUserUnseenInfoMessage) super.set(fieldName, value);
  }

  @Override
  public MainUserUnseenInfoMessage clone() {
    return (MainUserUnseenInfoMessage) super.clone();
  }

}
