/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://github.com/google/apis-client-generator/
 * (build: 2016-05-27 16:00:31 UTC)
 * on 2016-07-06 at 19:30:55 UTC 
 * Modify at your own risk.
 */

package com.appspot.recipex_1281.recipexServerApi.model;

/**
 * Message to return a list of Active Ingredients Summary: This message class is intended to be a
 * wrapper for a response message which returns as additional payload a list of
 * ActiveIngredientMessage. Attributes: active_ingredients = List of ActiveIngredientMessage to be
 * returned response = DefaultResponseMessage containing the response
 *
 * <p> This is the Java data model class that specifies how to parse/serialize into the JSON that is
 * transmitted over HTTP when working with the recipexServerApi. For a detailed explanation see:
 * <a href="https://developers.google.com/api-client-library/java/google-http-java-client/json">https://developers.google.com/api-client-library/java/google-http-java-client/json</a>
 * </p>
 *
 * @author Google, Inc.
 */
@SuppressWarnings("javadoc")
public final class MainActiveIngredientsMessage extends com.google.api.client.json.GenericJson {

  /**
   * Message to specify Active Ingredient's informations Summary: This message class is intended to
   * contain all the informations for a specific Active Ingredient entity. Attributes: name = Active
   * Ingredient's name id = Datastore id of the Active Ingredient entity response =
   * DefaultResponseMessage containing the response
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key("active_ingredients")
  private java.util.List<MainActiveIngredientMessage> activeIngredients;

  /**
   * A generic response message Summary: This message class is intended for returning a generic
   * response. Attributes: code = HTTP code of the response [REQUIRED] message = Text message of the
   * response [REQUIRED] doOperation = Boolean value to determine if there's an operation to do
   * according to the response payload = Optional textual payload of the response user =
   * RegisterUserMessage of a related invocation
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private MainDefaultResponseMessage response;

  /**
   * Message to specify Active Ingredient's informations Summary: This message class is intended to
   * contain all the informations for a specific Active Ingredient entity. Attributes: name = Active
   * Ingredient's name id = Datastore id of the Active Ingredient entity response =
   * DefaultResponseMessage containing the response
   * @return value or {@code null} for none
   */
  public java.util.List<MainActiveIngredientMessage> getActiveIngredients() {
    return activeIngredients;
  }

  /**
   * Message to specify Active Ingredient's informations Summary: This message class is intended to
   * contain all the informations for a specific Active Ingredient entity. Attributes: name = Active
   * Ingredient's name id = Datastore id of the Active Ingredient entity response =
   * DefaultResponseMessage containing the response
   * @param activeIngredients activeIngredients or {@code null} for none
   */
  public MainActiveIngredientsMessage setActiveIngredients(java.util.List<MainActiveIngredientMessage> activeIngredients) {
    this.activeIngredients = activeIngredients;
    return this;
  }

  /**
   * A generic response message Summary: This message class is intended for returning a generic
   * response. Attributes: code = HTTP code of the response [REQUIRED] message = Text message of the
   * response [REQUIRED] doOperation = Boolean value to determine if there's an operation to do
   * according to the response payload = Optional textual payload of the response user =
   * RegisterUserMessage of a related invocation
   * @return value or {@code null} for none
   */
  public MainDefaultResponseMessage getResponse() {
    return response;
  }

  /**
   * A generic response message Summary: This message class is intended for returning a generic
   * response. Attributes: code = HTTP code of the response [REQUIRED] message = Text message of the
   * response [REQUIRED] doOperation = Boolean value to determine if there's an operation to do
   * according to the response payload = Optional textual payload of the response user =
   * RegisterUserMessage of a related invocation
   * @param response response or {@code null} for none
   */
  public MainActiveIngredientsMessage setResponse(MainDefaultResponseMessage response) {
    this.response = response;
    return this;
  }

  @Override
  public MainActiveIngredientsMessage set(String fieldName, Object value) {
    return (MainActiveIngredientsMessage) super.set(fieldName, value);
  }

  @Override
  public MainActiveIngredientsMessage clone() {
    return (MainActiveIngredientsMessage) super.clone();
  }

}
